// <auto-generated />
using System;
using AgendaConsultorio.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaConsultorio.Migrations
{
    [DbContext(typeof(ConsultorioContexto))]
    partial class ConsultorioContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaConsultorio.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Agenda")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CPF")
                        .HasColumnName("CPF_Paciente_Agenda")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnName("Data_Consulta")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("DataHoraConsulta")
                        .HasColumnName("DATA_Hora_Consulta")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("HoraFinal")
                        .HasColumnName("Hora_Final")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("HoraInicial")
                        .HasColumnName("Hora_Inicial")
                        .HasColumnType("DATETIME");

                    b.Property<int>("PacienteID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteID");

                    b.ToTable("Tbl_Agenda");
                });

            modelBuilder.Entity("AgendaConsultorio.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Paciente")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CPF")
                        .HasColumnName("CPF_Paciente")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("Data_Nascimento")
                        .HasColumnType("DATE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome_Paciente")
                        .HasColumnType("VARCHAR(90)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Paciente");
                });

            modelBuilder.Entity("AgendaConsultorio.Models.Agenda", b =>
                {
                    b.HasOne("AgendaConsultorio.Models.Paciente", "Paciente")
                        .WithMany("Agendas")
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
